---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp politica-de-privacidade.html $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R Assets $DEPLOYPATH