# Generated by Django 4.2.25 on 2025-10-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=120)),
                ("whats", models.CharField(max_length=60)),
                ("cidade", models.CharField(max_length=80)),
                ("valor_conta", models.DecimalField(decimal_places=2, max_digits=10)),
                ("consent", models.BooleanField(default=False)),
                ("recaptcha_score", models.FloatField(blank=True, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
